using System;

namespace AppTraining.Models.Item
{
    public class OITM
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string FrgnName { get; set; }
        public short ItmsGrpCod { get; set; }
        public short CstGrpCode { get; set; }
        public string VatGourpSa { get; set; }
        public string CodeBars { get; set; }
        public string VATLiable { get; set; }
        public string PrchseItem { get; set; }
        public string SellItem { get; set; }
        public string InvntItem { get; set; }
        public decimal OnHand { get; set; }
        public decimal IsCommited { get; set; }
        public decimal OnOrder { get; set; }
        public string IncomeAcct { get; set; }
        public string ExmptIncom { get; set; }
        public decimal MaxLevel { get; set; }
        public string DfltWH { get; set; }
        public string CardCode { get; set; }
        public string SuppCatNum { get; set; }
        public string BuyUnitMsr { get; set; }
        public decimal NumInBuy { get; set; }
        public decimal ReorderQty { get; set; }
        public decimal MinLevel { get; set; }
        public decimal LstEvlPric { get; set; }
        public DateTime LstEvlDate { get; set; }
        public decimal CustomPer { get; set; }
        public string Canceled { get; set; }
        public int MnufctTime { get; set; }
        public string WholSlsTax { get; set; }
        public string RetilrTax { get; set; }
        public decimal SpcialDisc { get; set; }
        public short DscountCod { get; set; }
        public string TrackSales { get; set; }
        public string SalUnitMsr { get; set; }
        public decimal NumInSale { get; set; }
        public decimal Consig { get; set; }
        public int QueryGroup { get; set; }
        public decimal Counted { get; set; }
        public decimal OpenBlnc { get; set; }
        public string EvalSystem { get; set; }
        public short UserSign { get; set; }
        public string FREE { get; set; }
        public string PicturName { get; set; }
        public string Transfered { get; set; }
        public string BlncTrnsfr { get; set; }
        public string UserText { get; set; }
        public string SerialNum { get; set; }
        public decimal CommisPcnt { get; set; }
        public decimal CommisSum { get; set; }
        public short CommisGrp { get; set; }
        public string TreeType { get; set; }
        public decimal TreeQty { get; set; }
        public decimal LastPurPrc { get; set; }
        public string LastPurCur { get; set; }
        public DateTime LastPurDat { get; set; }
        public string ExitCur { get; set; }
        public decimal ExitPrice { get; set; }
        public string ExitWH { get; set; }
        public string AssetItem { get; set; }
        public string WasCounted { get; set; }
        public string ManSerNum { get; set; }
        public decimal SHeight1 { get; set; }
        public short SHght1Unit { get; set; }
        public decimal SHeight2 { get; set; }
        public short SHght2Unit { get; set; }
        public decimal SWidth1 { get; set; }
        public short SWdth1Unit { get; set; }
        public decimal SWidth2 { get; set; }
        public short SWdth2Unit { get; set; }
        public decimal SLength1 { get; set; }
        public short SLen1Unit { get; set; }
        public decimal Slength2 { get; set; }
        public short SLen2Unit { get; set; }
        public decimal SVolume { get; set; }
        public short SVolUnit { get; set; }
        public decimal SWeight1 { get; set; }
        public short SWght1Unit { get; set; }
        public decimal SWeight2 { get; set; }
        public short SWght2Unit { get; set; }
        public decimal BHeight1 { get; set; }
        public short BHght1Unit { get; set; }
        public decimal BHeight2 { get; set; }
        public short BHght2Unit { get; set; }
        public decimal BWidth1 { get; set; }
        public short BWdth1Unit { get; set; }
        public decimal BWidth2 { get; set; }
        public short BWdth2Unit { get; set; }
        public decimal BLength1 { get; set; }
        public short BLen1Unit { get; set; }
        public decimal Blength2 { get; set; }
        public short BLen2Unit { get; set; }
        public decimal BVolume { get; set; }
        public short BVolUnit { get; set; }
        public decimal BWeight1 { get; set; }
        public short BWght1Unit { get; set; }
        public decimal BWeight2 { get; set; }
        public short BWght2Unit { get; set; }
        public string FixCurrCms { get; set; }
        public short FirmCode { get; set; }
        public DateTime LstSalDate { get; set; }
        public string QryGroup1 { get; set; }
        public string QryGroup2 { get; set; }
        public string QryGroup3 { get; set; }
        public string QryGroup4 { get; set; }
        public string QryGroup5 { get; set; }
        public string QryGroup6 { get; set; }
        public string QryGroup7 { get; set; }
        public string QryGroup8 { get; set; }
        public string QryGroup9 { get; set; }
        public string QryGroup10 { get; set; }
        public string QryGroup11 { get; set; }
        public string QryGroup12 { get; set; }
        public string QryGroup13 { get; set; }
        public string QryGroup14 { get; set; }
        public string QryGroup15 { get; set; }
        public string QryGroup16 { get; set; }
        public string QryGroup17 { get; set; }
        public string QryGroup18 { get; set; }
        public string QryGroup19 { get; set; }
        public string QryGroup20 { get; set; }
        public string QryGroup21 { get; set; }
        public string QryGroup22 { get; set; }
        public string QryGroup23 { get; set; }
        public string QryGroup24 { get; set; }
        public string QryGroup25 { get; set; }
        public string QryGroup26 { get; set; }
        public string QryGroup27 { get; set; }
        public string QryGroup28 { get; set; }
        public string QryGroup29 { get; set; }
        public string QryGroup30 { get; set; }
        public string QryGroup31 { get; set; }
        public string QryGroup32 { get; set; }
        public string QryGroup33 { get; set; }
        public string QryGroup34 { get; set; }
        public string QryGroup35 { get; set; }
        public string QryGroup36 { get; set; }
        public string QryGroup37 { get; set; }
        public string QryGroup38 { get; set; }
        public string QryGroup39 { get; set; }
        public string QryGroup40 { get; set; }
        public string QryGroup41 { get; set; }
        public string QryGroup42 { get; set; }
        public string QryGroup43 { get; set; }
        public string QryGroup44 { get; set; }
        public string QryGroup45 { get; set; }
        public string QryGroup46 { get; set; }
        public string QryGroup47 { get; set; }
        public string QryGroup48 { get; set; }
        public string QryGroup49 { get; set; }
        public string QryGroup50 { get; set; }
        public string QryGroup51 { get; set; }
        public string QryGroup52 { get; set; }
        public string QryGroup53 { get; set; }
        public string QryGroup54 { get; set; }
        public string QryGroup55 { get; set; }
        public string QryGroup56 { get; set; }
        public string QryGroup57 { get; set; }
        public string QryGroup58 { get; set; }
        public string QryGroup59 { get; set; }
        public string QryGroup60 { get; set; }
        public string QryGroup61 { get; set; }
        public string QryGroup62 { get; set; }
        public string QryGroup63 { get; set; }
        public string QryGroup64 { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime UpdateDate { get; set; }
        public string ExportCode { get; set; }
        public decimal SalFactor1 { get; set; }
        public decimal SalFactor2 { get; set; }
        public decimal SalFactor3 { get; set; }
        public decimal SalFactor4 { get; set; }
        public decimal PurFactor1 { get; set; }
        public decimal PurFactor2 { get; set; }
        public decimal PurFactor3 { get; set; }
        public decimal PurFactor4 { get; set; }
        public string SalFormula { get; set; }
        public string PurFormula { get; set; }
        public string VatGroupPu { get; set; }
        public decimal AvgPrice { get; set; }
        public string PurPackMsr { get; set; }
        public decimal PurPackUn { get; set; }
        public string SalPackMsr { get; set; }

    }
}
